name: Git Tag
desciption: Tag commit with version number

runs:
  using: composite
  container: alpine/git
  steps:
    - run: |
        TAG=$(git describe --abbrev=0 --tags)
        git tag -f "$TAG" "$GITHUB_SHA"
        git push -f origin "$TAG"
