name: Git Checkout
desciption: Checkout repository using alpite/git

runs:
  using: composite
  container: alpine/git
  steps:
    - name: Checkout repository
      uses: addnab/docker-run-action@v3
      with:
        image: alpine/git:latest
        options: -v ${{ github.workspace }}:/git
        run: |
          HOST=$(echo "${{ github.server_url }}" | sed 's%https://%%')
          URL="https://${{ github.token }}@$HOST/${{ github.repository }}.git"
          git clone -b "${{ github.ref_name  }}" "$URL" .
          git status && ls
