name: Checkout
desciption: Git clone reposirory

inputs:
  url:
    type: string
    required: false
    description: Repository URL that will be cloned
    default: ${{github.server_url}}/${{github.repository}}.git
  token:
    type: string
    required: false
    description: Authentication token
    default: ${{github.token}}

runs:
  using: composite
  steps:
    - name: Creat authorized Git URL
      run: echo "URL=$(echo ${{inputs.url}} | sed s%://%://${{inputs.token}}@% )" >> $GITHUB_ENV
      shell: sh
    - name: Clone repository
      uses: docker://alpine/git
      with:
        entrypoint: git
        args: clone -b "${{github.ref_name}}" "${{env.URL}}" .
