name: Compress Files
desciption: Compress files into a gziped archive

inputs:
  pattern:
    required: true
    type: string
  out:
    requried: false
    type: string
    default: archive.tar.gz

runs:
  using: composite
  container: alpine
  steps:
    - run: |
        tar -czvf archive.tar,gz $(find . -type f -name "${{ inputs.pattern }}" )
