name: NPM Publish
description: Push to registry

inputs:
  registry:
    type: string
    required: false
    description: NPM registry FQDM
    default: ${{github.server_url}}
  owner:
    type: string
    required: false
    description: Owner to publish to
    default: ${{github.repository_owner}}
  token:
    type: string
    required: false
    description: Access Token
    default: ${{secrets.DEPLOY_TOKEN}}
  branch:
    type: string
    required: false
    description: Only publish for branch
    default: develop

runs:
  using: composite
  steps:
    - name: Setup registry
      run: |
        if [ "${{github.ref_name}}" == "${{inputs.branch}}" ]; then
          TRIMMED=$(echo "${{inputs.registry}}" | sed s%http:%% | sed s%https:%%)
          echo "_authToken=${{inputs.token}}" > .npmrc
          echo "registry=$TRIMMED/api/packages/${{inputs.owner}}/npm/" >> .npmrc
        fi
      shell: sh

    - name: Publish
      uses: docker://node
      with:
        args: /bin/bash -c "[[ ${{github.ref_name}} == ${{inputs.branch}} ]] && npm publish"
