name: NPM Publish
description: Push to registry

inputs:
  owner:
    type: string
    required: false
    description: Owner to publish to
    default: ${{github.repository_owner}}
  registry:
    type: string
    required: false
    description: NPM registry FQDM
    default: ${{github.server_url}}/api/packages/${{inputs.owner}}/npm/
  token:
    type: string
    required: false
    description: Access Token
    default: ${{secrets.DEPLOY_TOKEN}}
  branch:
    type: string
    required: false
    description: Only publish for branch
    default: develop

runs:
  using: composite
  steps:
    - name: Publish
      if: ${{github.ref_name}} == ${{inputs.branch}}
      uses: docker://node
      with:
        args: /bin/bash -c 'npm config set registry ${{inputs.registry}} && npm config set -- $(echo ${{inputs.registry}} | sed s%http:%% | sed s%https:%% ):_authToken "${{inputs.token}}" && npm publish'
