name: Docker Login
description: Login to Docker Registry

inputs:
  registry:
    type: string
    required: false
    default: ${{github.server_url}}
  user:
    type: string
    required: false
    default: ${{github.repository_owner}}
  password:
    type: string
    required: false
    default: ${{secret.DEPLOY_TOKEN}}

runs:
  using: composite
  steps:
    - name: Creat Image Tag
      run: echo "URL=$(echo ${{github.server_url}} | sed s%http://%% | sed s%https://%% )" >> $GITHUB_ENV
      shell: sh
    - run: echo docker login -u "${{inputs.user}}" --password "${{inputs.password}}" "${{env.URL}}"
      shell: sh
    - name: Docker Login
      uses: docker://docker
      with:
        entrypoint: docker
        args: login -u "${{inputs.user}}" --password "${{inputs.password}}" "${{env.URL}}"
