name: Docker Push
description: Push docker image to registry

inputs:
  registry:
    type: string
    required: false
    default: ${{github.server_url}}
  name:
    type: string
    required: false
    default: ${{github.repository}}
  tag:
    type: string
    required: false
    default: ${{github.ref_name}}

runs:
  using: composite
  steps:
    - name: Docker Login
      uses: docker://docker
      with:
        entrypoint: docker
        args: push "${{inputs.registry}}/${{inputs.name}}:${{inputs.tag}}"
