name: Docker Push
description: Push docker image to registry

inputs:
  registry:
    type: string
    required: false
    default: ${{github.server_url}}
  name:
    type: string
    required: false
    default: ${{github.repository}}
  tag:
    type: string
    required: false
    default: ${{github.ref_name}}

runs:
  using: composite
  steps:
    - name: Creat Image Tag
      run: echo "URL=$(echo ${{github.server_url}} | sed s%http://%% | sed s%https://%% )" >> $GITHUB_ENV
      shell: sh
    - name: Docker Push
      uses: docker://docker
      with:
        entrypoint: docker
        args: push "${{env.URL}}/${{inputs.name}}:${{inputs.tag}}"
