name: Tag
desciption: Create Git tag

inputs:
  tag:
    type: string
    required: true
    description: Tag to publish

runs:
  using: composite
  steps:
    - name: Create Tag
      uses: docker://alpine/git
      with:
        entrypoint: git
        args: tag -f ${{inputs.tag}} ${{github.sha}}
  
    - name: Push Tag
      uses: docker://alpine/git
      with:
        entrypoint: git
        args: push -f origin ${{inputs.tag}}
