name: Tag Repository

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  tag:
    name: Tag Repository
    if: $GITHUB_REF_NAME == "${{ inputs.branch }}"
    runs-on: ubuntu-latest
    steps:
      - uses: ztimson/actions/git/checkout@develop
      - uses: ztimson/actions/git/tag@develop
