name: Link Workspace
desciption: Connect persistant storage to workspace

runs:
  using: composite
  steps:
    - run: |
        PERSISTANT="/cache/workspace/${{ github.job }}"
        mkdir -p "$PERSISTANT"
        WORKSPACE=$(pwd)
        cd ..
        rm -rf "$WORKSPACE"
        ln -fs "$PERSISTANT" "$WORKSPACE"
        echo "Linked: $PERSISTANT -> $WORKSPACE"
        echo "Workspace will be automatically deleted in 1 hour"
        sleep 3600 && rm -rf "$PERSISTANT" &
      shell: sh
