name: Link Workspace
desciption: Connect persistant storage to workspace

inputs:
  key:
    required: true
    type: string
    default: default

runs:
  using: composite
  steps:
    - run: |
        WORKSPACE=$(pwd)
        cd ..
        rm -rf "$WORKSPACE"
        mkdir -p "/cache/workspace/${{ inputs.key }}"
        ln -fs "/cache/workspace/${{ inputs.key }}" "$WORKSPACE"
        echo "Linked: /cache/workspace/${{ inputs.key }} -> $WORKSPACE"
