name: Link Workspace
desciption: Connect persistant storage to workspace

inputs:
  key:
    required: true
    type: string
    default: default

runs:
  using: composite
  steps:
    - run: |
        WORKSPACE=$(pwd)
        cd ..
        ln -fs "/workspace/${{ inputs.key }}" "$WORKSPACE"
        echo "Linked: /workspace/${{ inputs.key }} -> $WORKSPACE"
