name: Load Workspace
description: Switch to job's persistant workspace

inputs:
  key:
    required: true
    type: string

runs:
  using: composite
  steps:
    - run: |
        WORKSPACE=$(pwd)
        cd ..
        ln -fs "/workspace/${{ inputs.key }}" "$WORKSPACE"
        echo "Linked: /workspace/${{ inputs.key }} -> $WORKSPACE"
