name: Load Workspace
description: Switch to job's persistant workspace

input:
  key:
    type: string
    required: true
    description: Workspace ID

runs:
  using: composite
  steps:
    - run: |
        WORKSPACE=$(pwd)
        cd ..
        rm -rf "$WORKSPACE"
        mkdir -p "/workspace/${{inputs.key}}"
        ln -s "/workspace/${{inputs.key}}" "$WORKSPACE"
        echo "Linked: /workspace/${{inputs.key}} -> $WORKSPACE"
