name: Link Workspace
desciption: Connect persistant storage to workspace

inputs:
  key:
    type: string
    required: false
    default: ${{ github.run_id }}

runs:
  using: composite
  steps:
    - run: |
        PERSISTANT="/cache/workspace/${{ inputs.key }}"
        mkdir -p "$PERSISTANT"
        WORKSPACE=$(pwd)
        cd ..
        rm -rf "$WORKSPACE" || sleep 5 && rm -rf "$WORKSPACE" || sleep 5 && rm -rf "$WORKSPACE"
        ln -fs "$PERSISTANT" "$WORKSPACE"
        echo "Linked: $PERSISTANT -> $WORKSPACE"
        echo "Workspace will be automatically deleted in 1 hour"
        sleep 3600 && rm -rf "$PERSISTANT" &
      shell: sh
