name: Load Workspace
description: Switch to job's persistant workspace

input:
  key:
    required: true
    type: string

runs:
  using: composite
  steps:
    - run: |
        WORKSPACE=$(pwd)
        cd ..
        ln -fs "/workspace/$KEY" "$WORKSPACE"
        echo "Linked: /workspace/$KEY -> $WORKSPACE"
      shell: bash
      env:
        KEY: ${{ inputs.key }}
